apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-backup-s3
  namespace: asmblyr-data
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: yandex-lockbox-wif
    kind: SecretStore
  target:
    name: postgres-backup-s3
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: ""
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: <LOCKBOX_SECRET_ID>
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: <LOCKBOX_SECRET_ID>
        property: ACCESS_SECRET_KEY
