apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: yandex-lockbox-wif
  namespace: asmblyr-data
spec:
  provider:
    webhook:
      url: >-
        http://127.0.0.1:8081/v1/secrets/{{ .remoteRef.key }}?property={{ .remoteRef.property }}
      method: GET
      timeout: 10s
      result:
        jsonPath: $.value
