apiVersion: kubelet.config.k8s.io/v1
kind: CredentialProviderConfig
providers:
  - name: ycr-credential-provider
    matchImages:
      - cr.yandex
    defaultCacheDuration: 10m
    apiVersion: credentialprovider.kubelet.k8s.io/v1
    tokenAttributes:
      serviceAccountTokenAudience: asmblyr-ycr
      cacheType: ServiceAccount
      requireServiceAccount: true
      requiredServiceAccountAnnotationKeys:
        - yandex.cloud/federated-yc-service-account-id
